# Generated by Django 5.1.5 on 2025-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('NEWSPAPER', 'NEWSPAPER'), ('PRODUCT', 'PRODUCT')], default='PRODUCT', max_length=50)),
                ('monday_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuesday_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wednesday_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('thursday_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('friday_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saturday_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sunday_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
