# Generated by Django 5.1.5 on 2025-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=255)),
                ('date_yape', models.DateField(blank=True, null=True)),
                ('operation_code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
