# Generated by Django 5.1.5 on 2025-12-12 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail_assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('devolution_date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('detail_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail_assignment.detailassignment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
