# Generated by Django 5.1.5 on 2025-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_finance', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_operation', models.CharField(choices=[('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE')])),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
