# Generated by Django 5.1.5 on 2025-12-12 03:15

import seller.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('number_seller', models.CharField(max_length=20, unique=True, validators=[seller.validators.validate_is_number, seller.validators.validate_no_spaces])),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('phone', models.CharField(default='', max_length=9)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
