# Generated by Django 5.1.5 on 2026-02-09 04:46

import seller.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='number_seller',
            field=models.CharField(max_length=20, unique=True, validators=[seller.validators.validate_no_spaces]),
        ),
    ]
