# Generated by Django 5.1.5 on 2025-12-12 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('returns_date', models.IntegerField(default=0)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status_product', models.BooleanField(default=False)),
                ('total_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('type_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='type_product.typeproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
