# Generated by Django 5.1.5 on 2026-01-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_reserved_quantity'),
        ('type_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'type_product', 'date')},
        ),
    ]
