# Generated by Django 5.1.5 on 2026-02-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_date_and_add_assignments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
