# Generated by Django 5.1.5 on 2026-02-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=5, null=True),
        ),
    ]
