# Generated by Django 5.1.5 on 2026-02-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_base_price_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=5, null=True),
        ),
    ]
