# Generated by Django 5.1.5 on 2025-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_cash', models.DateField()),
                ('type_product', models.CharField(choices=[('OJO', 'OJO'), ('COMERCIO', 'COMERCIO')], default='COMERCIO', max_length=8)),
                ('two_hundred', models.IntegerField(blank=True, null=True)),
                ('one_hundred', models.IntegerField(blank=True, null=True)),
                ('fifty', models.IntegerField(blank=True, null=True)),
                ('twenty', models.IntegerField(blank=True, null=True)),
                ('ten', models.IntegerField(blank=True, null=True)),
                ('five', models.IntegerField(blank=True, null=True)),
                ('two', models.IntegerField(blank=True, null=True)),
                ('one', models.IntegerField(blank=True, null=True)),
                ('fifty_cents', models.IntegerField(blank=True, null=True)),
                ('twenty_cents', models.IntegerField(blank=True, null=True)),
                ('ten_cents', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
